name: vercel_dart_runtime
description: A utility library for writing serverless functions in the Vercel Dart Runtime.
version: 1.0.1
repository: https://github.com/amondnet/vercel-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  aws_lambda_runtime: ^1.1.1
  json_annotation: ^4.1.0
  shelf: ^1.2.0

dev_dependencies:
  build_runner: ^2.0.6
  json_serializable: ^5.0.0
  lints: ^1.0.1
  test: ^1.17.10
